# Generated by Django 4.2.7 on 2025-08-29 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0002_rename_admin_phone_institution_academicyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='adminEmail',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='adminName',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='adminPhone',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='id',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='principalEmail',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='principalName',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='principalPhone',
        ),
        migrations.AddField(
            model_name='institution',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_institution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='principal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_institution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institutionCode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
