# Generated by Django 4.2.7 on 2025-08-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_remove_institution_adminemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institutionLogo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/logos/'),
        ),
        migrations.CreateModel(
            name='InstitutionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='institutions/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='institution.institution')),
            ],
        ),
    ]
